### ISSUE TITLE
Printing Timeout in the app logs

### ISSUE THREAD

**Issue by Ajju2211** [ibnux/Android-SMS-Gateway#7]
After hitting your API with required fields,
I am getting like this
```
{"multicast_id":4231954657571255714,"success":1,"failure":0,"canonical_ids":0,"results":[{"message_id":"0:1625429707507780%c47ae36ef9fd7ecd"}]}
```
I thing the API returned success, but in the app logs its printing like this.
```
TIMEOUT 2021-7-5 1:44:49 <MY_NUMBER> hello
```
I tried building my own server using firebase FCM but it returns MismatchSenderId error
```
{
 multicast_id: 4066263650481949700,  success: 0,  failure: 1,  canonical_ids: 0,  results: [ { error: 'MismatchSenderId' } ]
}
```
What I need to do, Please help me out.

Thanks in advance.

**Comment by ibnux** [comment]
Timeout because you send different **time** with the device
server or sender time need to be the same with device time. if 1 hour different, it will be timeout or expired

https://github.com/ibnux/Android-SMS-Gateway/blob/2a253e342af58939ddc49dde7a6d82cabe4c7c6d/app/src/main/java/com/ibnux/smsgateway/layanan/PushService.java#L157

if you use your own Firebase account, you need to build your own android release with firebase configuration

**Comment by Ajju2211** [comment]
After adding my firebase google-service.json and rebuilding the APK its working now.
Thank you.
